quotes = [
["To go wrong in one's own way is better than to go right in someone else's.","Crime and Punishment"],
["Taking a new step, uttering a new word, is what people fear most.", "Crime and Punishment"],
["Your worst sin is that you have destroyed and betrayed yourself for nothing.","Crime and Punishment"],
["Pain and suffering are always inevitable for a large intelligence and a deep heart.","Crime and Punishment"],
["The man who has a conscience suffers whilst acknowledging his sin. That is his punishment.","Crime and Punishment"],
["When reason fails, the devil helps!","Crime and Punishment"],
["I did not bow down to you, I bowed down to all the suffering of humanity.","Crime and Punishment"],
["A hundred suspicions don't make a proof.","Crime and Punishment"],
["Power is given only to him who dares to stoop and take it ... one must have the courage to dare.","Crime and Punishment"],
["The fear of appearances is the first symptom of impotence.","Crime and Punishment"],
["Man grows used to everything, the scoundrel!","Crime and Punishment"],
["Man has it all in his hands, and it all slips through his fingers from sheer cowardice.","Crime and Punishment"],
["Only to live, to live and live! Life, whatever it may be!","Crime and Punishment"],
["Truly great men must, I think, experience great sorrow on the earth.","Crime and Punishment"],
["Break what must be broken, once for all, that's all, and take the suffering on oneself.","Crime and Punishment"],
["You see I kept asking myself then: why am I so stupid that if others are stupid—and I know they are—yet I won't be wiser?","Crime and Punishment"],
["What do you think, would not one tiny crime be wiped out by thousands of good deeds?","Crime and Punishment"],
["And though I suffer for you, yet it eases my heart to suffer for you.","Poor Folk"],
["There is a crack in my soul, and I can hear it trembling, quivering, stirring deep inside me.","Poor Folk"],
["Poor people are subject to fancies — this is a provision of nature.","Poor Folk"],
["We mortals who dwell in pain and sorrow might with reason envy the birds of heaven which know not either!","Poor Folk"],
["Day succeeded day, and each day was like the last one.","Poor Folk"],
["whenever I try to describe anything with more than ordinary distinctness, I fall into the mistake of talking sheer rubbish.","Poor Folk"],
["Rich folk dislike hearing poor people complain of their poverty.","Poor Folk"],
["Yes, all that you have done to give me pleasure has become converted into a source of grief, and left behind it only useless regret.","Poor Folk"],
["I was too dreamy, and that saved me","Poor Folk"],
["most men love to see their best friend in abasement; for generally it is on such abasement that friendship is founded.","The Gambler"],
["But gamblers know how a man can sit for almost twenty-four hours at cards, without looking to right, or to left.","The Gambler"],
["Or perhaps it is because it is so NECESSARY for you to win. It is like a drowning man catching at a straw.","The Gambler"],
["What am I? I am zero—nothing. What shall I be tomorrow? I may be risen from the dead, and have begun life anew.","The Gambler"],
["Money must be so subservient to gentility as never to be worth a thought.","The Gambler"],
["Do not leave her alone so much as advise her, persuade her, draw her away. In any case do not let her gamble; find her some counter-attraction.","The Gambler"],
["As he passed I looked at him, and the thought occurred to me that he was a man lost for ever.","The Gambler"],
["I obeyed you simply because you ordered me to; but you must not blame me for the result.","The Gambler"],
["Invite a man to your table, and soon he will place his feet upon it.","The Gambler"],
["I have not a single human thought in my head.","The Gambler"],
["What is hell? I maintain that it is the suffering of being unable to love.","The Brothers Karamazov"],
["I love mankind, but I find to my amazement that the more I love mankind as a whole, the less I love man in particular.","The Brothers Karamazov"],
["The mystery of human existence lies not in just staying alive, but in finding something to live for.","The Brothers Karamazov"],
["I can see the sun, but even if I cannot see the sun, I know that it exists. And to know that the sun is there - that is living.","The Brothers Karamazov"],
["The awful thing is that beauty is mysterious as well as terrible. God and the devil are fighting there and the battlefield is the heart of man.","The Brothers Karamazov"],
["I think the devil doesn't exist, but man has created him, he has created him in his own image and likeness.","The Brothers Karamazov"],
["Besides, nowadays, almost all capable people are terribly afraid of being ridiculous, and are miserable because of it.","The Brothers Karamazov"],
["You will burn and you will burn out; you will be healed and come back again.","The Brothers Karamazov"],
["Love in action is a harsh and dreadful thing compared to love in dreams.","The Brothers Karamazov"],
["A beast can never be as cruel as a human being, so artistically, so picturesquely cruel.","The Brothers Karamazov"],
["Forgive me... for my love - for ruining you with my love.","The Brothers Karamazov"],
["They were like two enemies in love with one another.","The Brothers Karamazov"],
["I think I could stand anything, any suffering, only to be able to say and to repeat to myself every moment, 'I exist.' In thousands of agonies","The Brothers Karamazov"],
["Silence is the key to all mysteries.","Netochka Nezvanova"],
["In solitude, the mind finds answers that the world cannot provide.","Netochka Nezvanova"],
["True strength is not in fighting others, but in conquering yourself.","Netochka Nezvanova"],
["The scars of the past don't define your future, they shape it.","Netochka Nezvanova"],
["Sometimes, the most beautiful souls are the ones who have endured the greatest suffering.","Netochka Nezvanova"],
["Love is a flame that can either warm your heart or burn your soul.","Netochka Nezvanova"],
["We are all broken, but it's up to us to decide how to mend the pieces.","Netochka Nezvanova"],
["The dance of life is a delicate balance between pain and joy.","Netochka Nezvanova"],
["Memories hold the power to heal or haunt us.","Netochka Nezvanova"],
["Courage is not the absence of fear, but the strength to face it.","Netochka Nezvanova"],
["It was the exercise of my power that attracted me most.","Notes from Underground"],
["Here it is, here it is at last, the encounter with reality. . . . All is lost now!","Notes from Underground"],
["I say let the world go to hell, but I should always have my tea.","Notes from Underground"],
["An intelligent man cannot become anything seriously, and it is only the fool who becomes anything.","Notes from Underground"],
["To care only for well-being seems to me positively ill-bred. Whether it’s good or bad, it is sometimes very pleasant, too, to smash things.","Notes from Underground"],
["The best definition of man is: a being that goes on two legs and is ungrateful.","Notes from Underground"],
["the whole work of man really seems to consist in nothing but proving to himself every minute that he is a man and not a piano-key!","Notes from Underground"],
["Now answer me, sincerely, honestly, who lives past forty? I'll tell you who does: fools and scoundrels.","Notes from Underground"],
["But what can a decent man speak of with most pleasure? Answer: Of himself. Well, so I will talk about myself.","Notes from Underground"],
["In despair there are the most intense enjoyments, especially when one is very acutely conscious of the hopelessness of one's position.","Notes from Underground"],
["man is a frivolous and incongruous creature, and perhaps, like a chess player, loves the process of the game, not the end of it.","Notes from Underground"],
["But what can a decent man speak of with most pleasure? Answer: Of himself. Well, so I will talk about myself.","Notes from Underground"]
]